---
# tasks file for deploy_swap
- name: Set swap_file variable
  set_fact:
    swap_file: "{{swap_file_path}}"
  tags:
    - swap.set.file.path

- name: Check if swap file exists
  stat:
    path: "{{swap_file}}"
  register: swap_file_check
  tags:
    - swap.file.check

- name: Turn off swap
  command: swapoff -a
  when: not swap_file_check.stat.exists
  tags:
    - swap.turn.on

- name: Create swap file
  command: fallocate -l {{swap_file_size}} {{swap_file_path}}
  when: not swap_file_check.stat.exists
  tags:
    - swap.file.create

- name: Change swap file permissions
  file: path="{{swap_file_path}}"
        owner=root
        group=root
        mode=0600
  tags:
    - swap.file.permissions

- name: Format swap file
  command: "mkswap {{swap_file}}"
  when: not swap_file_check.stat.exists
  tags:
    - swap.file.mkswap

- name: Write swap entry in fstab
  mount: name=swap
         src={{swap_file}}
         fstype=swap
         opts=defaults
         passno=0
         dump=0
         state=present
  tags:
    - swap.fstab

- name: Turn on swap
  command: swapon -a
  when: not swap_file_check.stat.exists
  tags:
    - swap.turn.on

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: "{{swappiness}}"
  tags:
    - swap.set.swappiness

- name: reload sysctl parameters
  shell: "sysctl -p"
  register: sysctl_output

- debug: var=sysctl_output
